"""empty message

Revision ID: 505eab2abe13
Revises: 6d5fb5f4acba
Create Date: 2024-11-07 17:10:49.959263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505eab2abe13'
down_revision = '6d5fb5f4acba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_name'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
